Its 107 fixed a bug where multiple futureProjections could be added to a keyFactor
WWI2021G/scenario-manager pull request #34
Opened 2024-07-16 13:59 UTC by DonMarc00

2024-07-16 20:04 UTC, Weiberle17 commented on :q
Was ist das :rofl: 
Du hast die Datei nicht benannt oder kein Plan wo die herkommt?

2024-07-16 20:05 UTC, Weiberle17 commented on backend/src/controllers/dbController.ts
> +      console.log("KeyFactor ID: ", keyFactor_id);
Können auch weg nehm ich an

2024-07-16 20:11 UTC, Weiberle17 commented on frontend/src/components/sub/KeyFactorTable.tsx
> +    console.log(keyFactor);
Auch fürs entwickeln?

2024-07-16 20:12 UTC, Weiberle17 requested changes
Vor allem die erste Datei fixen

2024-07-17 08:21 UTC, DonMarc00 commented on :q
Ich glaube das ist irgendein buffer. Die ist :q bennant wtf....

2024-07-17 08:30 UTC, merged