ITS 105
WWI2021G/scenario-manager pull request #37
Opened 2024-07-18 20:43 UTC by Weiberle17

ProjectionBündel werden bestimmt und numPartInconsistencies auch
**Bevor** wir mergen:
- master mergen und Konflikte lösen
- pValue fehlt noch
- Sortieren und auf Anzahl begrenzen
- in Datenbank eintragen

Ich kümmer mich morgen um die restlichen Sachen. Wär cool wenn du schon mal drüber schauen könntest, vor allem ob du Sachen siehst die man direkt optimieren kann. Läuft auf meinem PC mit 5 Schlüsselfaktoren *bis jetzt* sehr gut.

2024-07-18 20:45 UTC, Weiberle17 commented on backend/src/services/dbService.ts
> +          `Influencing factor WITH name $ { newName } already EXISTS.`,
backtick wegmachen wegen Formattierung

2024-07-18 20:50 UTC, DonMarc00 commented on backend/src/controllers/dbController.ts
> +  async calculateProjectionBundles(req: Request, res: Response) {
Das ist eigentlich ein Service und gehört nicht in den dbController

2024-07-18 20:51 UTC, DonMarc00 commented on backend/src/controllers/dbController.ts
> +const findDoubleCombinations = (projections: FutureProjection[]): [FutureProjection, FutureProjection][] => {
Das alles auch. Vielleicht auch manche Funktionen als Utils

2024-07-18 20:52 UTC, DonMarc00 commented on backend/src/controllers/dbController.ts
> +      if (Object.prototype.hasOwnProperty.call(matrix, projRow)) {
Wild er benutzt einfach Protoptypen. Die Dinger habe ich bis heute nicht verstanden XD

2024-07-18 20:53 UTC, DonMarc00 commented on backend/src/controllers/dbController.ts
> +            const innerFP = futureProjections.find(fp => fp.getName() === projCol);
Da ein Fachkundiger Prof draufschauen wird: Refactor des zu innerFutureProjection und den Rest entsprechend

2024-07-18 20:55 UTC, DonMarc00 commented on backend/src/controllers/dbController.ts
> +    doubleCombinations.forEach((combo) => {
Diesen Step mit einem Kommentar erläutern. Der Gredankengang wird niemandem außer uns klar sein

2024-07-18 20:56 UTC, DonMarc00 commented on backend/src/controllers/dbController.ts
> +const copyBidirectional = (matrix: Map<FutureProjection, Map<FutureProjection, number>>, key1: FutureProjection, key2: FutureProjection): Map<FutureProjection, Map<FutureProjection, number>> => {
Besserer Funktionsname oder Kommentar. Schau mal ob du es mit einem Namen hinkriegst. Ansonsten halt Kommentar

2024-07-18 20:59 UTC, DonMarc00 requested changes
Sieht schonmal nicht verkehrt aus

2024-07-19 05:39 UTC, Weiberle17 commented on backend/src/controllers/dbController.ts
> +    doubleCombinations.forEach((combo) => {
Was hälst von dem?

2024-07-19 07:44 UTC, Weiberle17 commented
Es wird jetzt nur noch nicht überprüft, ob es für das ScenarioProjekt schon Bündel gibt. Das bedeutet wenn man die Matrix mehrmals abschickt werden die Bündel mehrmals eingefügt.
Denke wir können trotzdem mal mergen und dann schau ich mir das im nächsten Schritt an. Du solltest dann auch mit den Daten arbeiten können für die Clusteranalyse

2024-07-19 13:56 UTC, DonMarc00 commented on backend/src/controllers/dbController.ts
> +    doubleCombinations.forEach((combo) => {
Sollte fürs erste passen

2024-07-19 13:56 UTC, DonMarc00 approved these changes

2024-07-19 13:56 UTC, merged